### ISSUE TITLE
The background processor for API requests has failed citically.

### ISSUE THREAD

**Issue by patrick-petersen** [gw2scratch/evtc#188] opened 2023-05-17 20:37 UTC
I've downloaded the latest 1.8.0 self contained log manager for windows. Started it with the default configuration.
It found my logs, showed all logs as 14048 and all specifics (Raid, Strike etc) as 0.
After a few seconds I got this window:
![image](https://github.com/gw2scratch/evtc/assets/4784982/ec671c8f-a677-4b0a-b266-5d789a0d5c9b)
It is still working in the background (i.e. "Downloading guild data") and the logs are getting processed and sorted into their categories. This continued while the error message was still open, and after I closed it.

**Comment by patrick-petersen** [comment] 2023-05-17 21:04
Downloading guild data stopped at 23. After the processing was done I restarted the log manager, and got the same error message again. Now the "Downloading guild data" is stuck at "0/3030".

**Comment by Sejsel** [comment] 2023-05-25 09:43
This seems to be caused by the GW2 API suddenly starting to responding with an internal error (500), `{"text":"unknown error"}` to guilds that do not exist, which includes guilds that have been disbanded.

I am likely going to make the manager treat that as if it was not found until it gets fixed in the GW2 API (if that ever happens)

**Comment by Sejsel** [comment] 2023-08-02 17:40
Fixed with 1.9 🎉

**Closed by Sejsel** 2023-08-02 17:40 UTC
