### ISSUE TITLE
AI Only dark phase logs parse as "Both phases" now

### ISSUE THREAD

**Issue by GeneratedNickname** [gw2scratch/evtc#168] opened 2022-06-30 12:44 UTC
Old logs are untouched, new logs parse wrong.

"Now" is after upgrading from 1.5.0.2 to 1.6.0.1

**Comment by Sejsel** [comment] 2022-06-30 15:09
Thank you for the report :)

This is a regression caused by changing initial buff events to derive from buff apply events, and affects all Ai logs if they are reprocessed. Unfortunately the code that looked for Determined to be applied during the fight now sees the Determined that was applied at the start.

Will get it fixed as soon as I can, but I will probably be away from my computer for a about week.

**Comment by Sejsel** [comment] 2022-07-10 18:34
This is now fixed with 78bd89ccc22ca586779cef816157f5ab799ddef1. The next released version will contain the fix. Thanks again for reporting it!

I have also added an automatic test suite for logs (kill, failure, cm logs for each encounter; total of 134 logs) to ensure this doesn't happen again :)

**Closed by Sejsel** 2022-07-10 18:34 UTC
Labels: bug
