### ISSUE TITLE
Upload always fails for particular logs

### ISSUE THREAD

**Issue by myrasol** [gw2scratch/evtc#65] opened 2020-05-09 10:59 UTC
Hello,

Some of my logs always fail when i try to upload them while very similar logs have been uploaded without problem.

Here is an example that fails : 
[20200508-224133.zip](https://github.com/gw2scratch/evtc/files/4603309/20200508-224133.zip)

and here a similar log that succeeded : 
[20200508-222530.zip](https://github.com/gw2scratch/evtc/files/4603312/20200508-222530.zip)

Regards

**Comment by Sejsel** [comment] 2020-05-09 12:27
I can't reproduce the problem, both logs upload correctly for me. What is the exact message that appears instead of the uploaded url?

While this is unlikely to help as some logs work, https://dps.report has multiple regional endpoints that can be used to upload logs, you can try selecting a different one in the settings. Some areas of the world have bad connectivity to some of the endpoints.

**Comment by myrasol** [comment] 2020-05-09 13:20
th message is "Upload failed: Une tâche a été annulée."
I already try with all the region enpoints but i got the same issue.
It seems that i have the problem with logs that have a duration > 6 minutes.
i was thinking of maybe a timeout issue or something like that ?

**Comment by Sejsel** [comment] 2020-05-09 13:25
It looks like the default timeout is 100 seconds, which I can definitely see happening with slow connections. I will increase that value, probably to infinite.

**Comment by Sejsel** [comment] 2020-05-10 14:27
This should be fixed with fb08d8d26d7ead23d2945ddcaaf828adbe370e01, and will be included in the next released version. Thank you very much for the report!

**Closed by Sejsel** 2020-05-10 14:27 UTC
